import MaleyLean.Papers.ClaimStandingAndLegitimacy.PaperStatements
import MaleyLean.Papers.ClaimStandingAndLegitimacy.Surface.Summary

namespace MaleyLean

#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimFailureCoordinateExhaustionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperNoMissingPrimitiveCoordinateStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimStandingNecessityStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperStandingUnfixedIsNotWeakSupportStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperTargetCarrierAlignmentStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperFreedomExhaustionCriterionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperSkinCannotIncreaseLegitimacyStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperTensorVariationMustBeDeclaredOrClosedStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperLaunderingExclusionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperComputationAloneIsNotLegitimacyStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperAuthorityAloneIsNotStandingStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperCalibrationIsNotPredictionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperCalibrationOnlyTheoremStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperDeletionIsolationReplacementStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperBoundaryDeclarationPrincipleStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperNoIllicitStatusAmplificationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperReportPreservationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperBlockerPreservationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperUEAPCertificationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperUniqueStrongestStatusAssignmentStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperUEAPGovernanceBivalenceBridgeStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.SummaryStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.GovernanceBridgeSummaryStatement

end MaleyLean
