import MaleyLean.Papers.ClaimStandingAndLegitimacy.PaperStatements
import MaleyLean.Papers.ClaimStandingAndLegitimacy.Surface.Summary

namespace MaleyLean

#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimFailureCoordinateExhaustionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperNoMissingPrimitiveCoordinateStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimStandingNecessityStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimStandingFullNecessityStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperLegitimacyBlockerExclusionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperLegitimacyImpliesNoBlockerStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperLowerStatusIsNotLegitimacyStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperAuditFailureProducesValidatorOutputStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperSigmaLegitimacyProducesValidatorOutputStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperLowerStatusProducesValidatorOutputStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperStandingFailureProducesValidatorOutputStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperStandingUnfixedIsNotWeakSupportStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperTargetCarrierAlignmentStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperFreedomExhaustionCriterionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperSkinCannotIncreaseLegitimacyStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperTensorVariationMustBeDeclaredOrClosedStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperLaunderingExclusionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperComputationAloneIsNotLegitimacyStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperAuthorityAloneIsNotStandingStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperCalibrationIsNotPredictionStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperCalibrationOnlyTheoremStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperDeletionIsolationReplacementStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperBoundaryDeclarationPrincipleStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperNoIllicitStatusAmplificationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperReportPreservationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperBlockerPreservationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperAuditStatusMeaningSoundStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperSoundRegistryStrongestStatusStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimStandingNoSameActRepairStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimLegitimacyNoSameActRepairStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimStandingConservationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimLegitimacyConservationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimStandingClassifierUniquenessStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperClaimLegitimacyClassifierUniquenessStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperUEAPCertificationStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperUniqueStrongestStatusAssignmentStatement
#print axioms Papers.ClaimStandingAndLegitimacy.PaperUEAPGovernanceBivalenceBridgeStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.SummaryStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.GovernanceBridgeSummaryStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.RegistryStatusSoundnessSummaryStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.ClaimStandingNoRepairSummaryStatement
#print axioms Papers.ClaimStandingAndLegitimacy.Surface.ClaimStandingConservationSummaryStatement

end MaleyLean
