import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperStatements
import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.Surface.Summary

namespace MaleyLean

#print axioms Papers.MinimalConditionsForAdmissibleConstruction.Verbatim.manuscriptRoleStatesKernelUniqueness
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperConstructionForcesKernelStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperKernelNonDerivabilityStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperKernelPackageTransfersAcrossGovernanceEquivalenceStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperNothingDerivableBelowKernelStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperNoFaithfulLowerGeneratorStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperRouteExhaustionStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperNoFaithfulSameDomainExtensionStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperDerivationDependsOnConstructionalStandingStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperNoDeeperInvariantStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperMutualClosureStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperUniquenessOfGovernanceWorkStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperKernelUniquenessOnFixedDomainStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperFixedDomainClosurePacketStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperTransportQuotientAndDomainOperatorsStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperFoundationalClosureStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperInternalMechanizationBoundaryStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperGlobalSynthesisStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.PaperBivalenceBridgeStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.Surface.SummaryStatement
#print axioms Papers.MinimalConditionsForAdmissibleConstruction.Surface.BivalenceBridgeSummaryStatement

end MaleyLean
