import MaleyLean.Papers.YangMills.Kernel.APlusObligationLedger

namespace MaleyLean
namespace Papers
namespace YangMills

#eval ymAPlusObligations.map YMAPlusObligation.title
#eval ymAPlusObligations.map YMAPlusObligation.currentSocket

#check YMFixedLatticeGapAPlusCertificate
#check YMSharpLocalAPlusCertificate
#check YMContinuumTransportAPlusCertificate
#check YMOSWightmanAPlusCertificate
#check YMMinkowskiHamiltonianGapAPlusCertificate
#check YMEndpointExactnessAPlusCertificate
#check YMClayExtensionAPlusCertificate
#check ymAPlusAllCertificatesAvailable

#print axioms ymAPlusCertificates_require_fixed_lattice_gap
#print axioms ymAPlusCertificates_require_sharp_local_construction
#print axioms ymAPlusCertificates_require_continuum_transport
#print axioms ymAPlusCertificates_require_os_wightman_reconstruction
#print axioms ymAPlusCertificates_require_minkowski_hamiltonian_gap
#print axioms ymAPlusCertificates_require_endpoint_exactness_exclusion
#print axioms ymAPlusCertificates_require_clay_extension_admissibility
#print axioms ymAPlusFixedLatticeCertificate_requires_exact_theorem
#print axioms ymAPlusSharpLocalCertificate_requires_exact_theorem
#print axioms ymAPlusContinuumTransportCertificate_requires_exact_theorem
#print axioms ymAPlusOSWightmanCertificate_requires_exact_theorem
#print axioms ymAPlusMinkowskiCertificate_requires_exact_theorem
#print axioms ymAPlusEndpointCertificate_requires_exact_theorem
#print axioms ymAPlusClayExtensionCertificate_requires_exact_theorem
#print axioms ymAPlusCertificates_require_all_exact_theorems
#print axioms ymAPlusExactTheoremWitnessCount_eq
#print axioms ymAPlusFixedLatticeCertificate_requires_real_spectral_gap_payload
#print axioms ymAPlusFixedLatticeCertificate_requires_uniform_spectral_gap_payload
#print axioms ymAPlusFixedLatticeCertificate_requires_payload_bridge
#print axioms ymAPlusFixedLatticeCertificate_nonempty_of_payloads_bridge_transfer
#print axioms ymAPlusSharpLocalCertificate_requires_payload
#print axioms ymAPlusSharpLocalCertificate_requires_payload_bridge
#print axioms ymAPlusSharpLocalCertificate_nonempty_of_payload_bridge_transfer
#print axioms ymAPlusSharpLocalCertificate_nonempty_of_standard_import
#print axioms ymAPlusContinuumTransportCertificate_requires_payload
#print axioms ymAPlusContinuumTransportCertificate_requires_payload_bridge
#print axioms ymAPlusOSWightmanCertificate_requires_payload
#print axioms YMOSWightmanAPlusCertificate.requires_payload_bridge
#print axioms ymAPlusOSWightmanCertificate_nonempty_of_payload_bridge_background
#print axioms ymAPlusOSWightmanCertificate_nonempty_of_standard_import
#print axioms ymAPlusMinkowskiCertificate_requires_hamiltonian_payload
#print axioms ymAPlusMinkowskiCertificate_requires_payload_bridge
#print axioms ymAPlusMinkowskiCertificate_nonempty_of_payload_bridge_transfer_dynamics
#print axioms ymAPlusMinkowskiCertificate_nonempty_of_standard_import
#print axioms ymAPlusEndpointCertificate_requires_payload
#print axioms ymAPlusEndpointCertificate_requires_payload_bridge
#print axioms ymAPlusEndpointCertificate_nonempty_of_payload_bridge_transfer
#print axioms ymAPlusClayExtensionCertificate_requires_payload
#print axioms ymAPlusClayExtensionCertificate_requires_payload_bridge
#print axioms ymAPlusClayExtensionCertificate_nonempty_of_payload_bridge_transfer
#print axioms ymAPlusClayExtensionCertificate_nonempty_of_standard_import
#print axioms ymAPlusCertificates_require_all_non_dependent_payloads
#print axioms YMAPlusObligation.closed_of_certificate
#print axioms YMAPlusObligation.certificate_of_closed
#print axioms ymAPlusAllObligationsClosed_of_certificatesAvailable
#print axioms ymAPlusAllCertificatesAvailable_of_obligationsClosed
#print axioms ymAPlusClosure_requires_fixed_lattice_gap
#print axioms ymAPlusClosure_requires_sharp_local_construction
#print axioms ymAPlusClosure_requires_continuum_transport
#print axioms ymAPlusClosure_requires_os_wightman_reconstruction
#print axioms ymAPlusClosure_requires_minkowski_hamiltonian_gap
#print axioms ymAPlusClosure_requires_endpoint_exactness_exclusion
#print axioms ymAPlusClosure_requires_clay_extension_admissibility

end YangMills
end Papers
end MaleyLean
