import MaleyLean.Papers.YangMills.Kernel.APlusSourceCrosswalk

namespace MaleyLean
namespace Papers
namespace YangMills

#eval ymAPlusLocalNetSourceDocumentKeys
#eval ymAPlusLocalNetSourceDocumentFileNames
#eval ymAPlusLocalNetSourceDocumentsPopulatedBool
#eval ymAPlusExtractedSourceAnchorDocumentKeys
#eval ymAPlusExtractedSourceAnchorFiles
#eval ymAPlusExtractedSourceAnchorLabelLists
#eval ymAPlusExtractedSourceAnchorAvailabilityFlags
#eval ymAPlusExtractedSourceAnchorsPopulatedBool
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceDocumentKey
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceTheoremTitles
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceTheoremLabels
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceLabels
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceSupport.map
  (fun E =>
    (E.proofObligation, E.sourceDocumentKey,
      E.sourceTheorems.map ym_verbatim_theorem_title, E.sourceLabels))
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceSupportObligations
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceSupportDocumentKeys
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceSupportTheoremTitleLists
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceSupportLabelLists
#eval ymAPlusFixedLatticeHamiltonianDefinitionSourceSupportPopulatedBool
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceObligations
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceFields
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceProjections
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceDocumentKeys
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceTheoremTitleLists
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceLabelLists
#eval ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSourceSuppliedFlags
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationFields
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationPayloads
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationAnchorFiles
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationLabelLists
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationLeanTargets
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationSuppliedFlags
#eval ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationAllSuppliedBool
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceFields
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceTypes
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceCertificateFields
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceAnchorFiles
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceLabelLists
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceLeanTargets
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceSuppliedFlags
#eval ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceAllSuppliedBool
#eval ymAPlusLocalDegreesWitnessInputSourceFields
#eval ymAPlusLocalDegreesWitnessInputSourceRoles
#eval ymAPlusLocalDegreesWitnessInputSourceTargetShapes
#eval ymAPlusLocalDegreesWitnessInputSourceAnchorFiles
#eval ymAPlusLocalDegreesWitnessInputSourceLabelLists
#eval ymAPlusLocalDegreesWitnessInputSourceSupportRoles
#eval ymAPlusLocalDegreesWitnessInputSourceSuppliedFlags
#eval ymAPlusLocalDegreesWitnessInputSourceAllSuppliedBool
#eval ymAPlusLocalDegreesWitnessFieldDependencyFields
#eval ymAPlusLocalDegreesWitnessFieldDependencyProjections
#eval ymAPlusLocalDegreesWitnessFieldDependencyClasses
#eval ymAPlusLocalDegreesWitnessFieldDependencyLabelLists
#eval ymAPlusLocalDegreesWitnessFieldDependencyBlockingFlags
#eval ymAPlusLocalDegreesWitnessFieldDependencySuppliedFlags
#eval ymAPlusLocalDegreesWitnessFieldDependenciesAllBlockingBool
#eval ymAPlusLocalDegreesWitnessFieldDependenciesAllSuppliedBool
#eval ymAPlusLocalDegreesWitnessConstructorReadiness.targetConstructor
#eval ymAPlusLocalDegreesWitnessConstructorReadiness.dependencyCount
#eval ymAPlusLocalDegreesWitnessConstructorReadiness.requiredDependencyCount
#eval ymAPlusLocalDegreesWitnessConstructorReadinessFlags
#eval ymAPlusSourceCrosswalk.map (fun E => (E.title, E.auditFile))
#eval ymAPlusSourceCrosswalk_auditFiles
#eval ymAPlusFocusedObligationAuditFiles
#eval ymAPlusSourceCrosswalk_standardImportFiles
#eval ymAPlusCanonicalStandardImportFiles
#eval ymAPlusSourceCrosswalk_subobligationLedgers
#eval ymAPlusCanonicalSubobligationLedgers
#eval ymAPlusSourceCrosswalk_certificateTypes
#eval ymAPlusCanonicalCertificateTypes
#eval ymAPlusSourceCrosswalk_closureGates
#eval ymAPlusCanonicalClosureGates
#eval ymAPlusAuditedBundleProjectionCrosswalk.map
  (fun E => (E.title, E.certificateProjection, E.closureProjection))
#eval ymAPlusAuditedBundleProjectionCrosswalk_certificateTypes
#eval ymAPlusAuditedBundleProjectionCrosswalk_certificateProjections
#eval ymAPlusAuditedBundleProjectionCrosswalk_closureGates
#eval ymAPlusAuditedBundleProjectionCrosswalk_closureProjections
#eval ymAPlusAuditedBundleProjectionCrosswalk_populatedBool
#eval ymAPlusFocusedObligationAuditFiles
#eval ymAPlusGlobalAuditFiles
#eval ymAPlusAuditRunnerLeanFiles
#eval ymAPlusCanonicalAuditRunnerLeanFiles
#eval ymAPlusAuditRunnerLeanFilesPopulatedBool
#eval ymAPlusSourceCrosswalk_obligations
#eval ymAPlusSourceCrosswalk_titles
#eval ymAPlusSourceCrosswalk.map (fun E => (E.currentSocket, E.closureGate))
#eval ymAPlusSourceCrosswalk_currentSockets
#eval ymAPlusSourceCrosswalk_requiredClosures
#eval ymAPlusSourceCrosswalk.map
  (fun E => (E.subobligationLedger, E.subobligationCount))
#eval ymAPlusSourceCrosswalk_subobligationTotalCount
#eval ymAPlusSourceCrosswalk.map
  (fun E => (E.certificateType, E.exactTheoremProjection))
#eval ymAPlusSourceCrosswalk_exactTheoremProjections
#eval ymAPlusRequiredVerifiedHypothesisMapNames
#eval ymAPlusVerifiedHypothesisMapNames
#eval ymAPlusRequiredVerifiedHypothesisMapNamesPopulatedBool
#eval ymAPlusRequiredVerifiedHypothesisMapNamesDuplicateFreeBool
#eval ymAPlusHypothesisMapGapCrosswalk.map
  (fun E =>
    (E.title, E.exactTheoremProjection,
      E.requiredVerifiedHypothesisMap, E.verified))
#eval ymAPlusHypothesisMapGapCrosswalk_titles
#eval ymAPlusHypothesisMapGapCrosswalk_currentSockets
#eval ymAPlusHypothesisMapGapCrosswalk_standardImportFiles
#eval ymAPlusHypothesisMapGapCrosswalk_firstOpenSubobligations
#eval ymAPlusHypothesisMapGapCrosswalk_exactTheoremProjections
#eval ymAPlusHypothesisMapGapCrosswalk_routeHypothesisMaps
#eval ymAPlusCanonicalRouteHypothesisMapNames
#eval ymAPlusHypothesisMapGapCrosswalk_completionProjections
#eval ymAPlusCanonicalHypothesisMapCompletionProjections
#eval ymAPlusHypothesisMapGapCrosswalk_requiredMaps
#eval ymAPlusHypothesisMapGapCrosswalk_verifiedFlags
#eval ymAPlusHypothesisMapGapCrosswalk_allOpenBool
#eval ymAPlusSourceCrosswalk.map
  (fun E => (E.payloadProjection, E.standardSocketProjection))
#eval ymAPlusSourceCrosswalk_payloadProjections
#eval ymAPlusSourceCrosswalk_standardSocketProjections
#eval ymAPlusSourceCrosswalk.map
  (fun E => (E.payloadBridgeProjection, E.finalTargetProjection))
#eval ymAPlusSourceCrosswalk_payloadBridgeProjections
#eval ymAPlusSourceCrosswalk_finalTargetProjections
#eval ymAPlusSourceCrosswalk_globalAuditSurfaceProjections
#eval ymAPlusSourceCrosswalk_entries_match_bool
#eval ymAPlusSourceCrosswalk_entries_have_audit_surface_bool
#eval ymAPlusSourceCrosswalk_globalAuditSurfacePopulatedBool

#print axioms ymAPlusLocalNetSourceDocuments_count_eq
#print axioms ymAPlusLocalNetSourceDocumentFileNames_eq
#print axioms ymAPlusLocalNetSourceDocumentsPopulatedBool_eq_true
#print axioms ymAPlusExtractedSourceAnchors_count_eq
#print axioms ymAPlusExtractedSourceAnchorDocumentKeys_eq
#print axioms ymAPlusExtractedSourceAnchorFiles_eq
#print axioms ymAPlusExtractedSourceAnchorLabelLists_eq
#print axioms ymAPlusExtractedSourceAnchorAvailabilityFlags_eq
#print axioms ymAPlusExtractedSourceAnchorsPopulatedBool_eq_true
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceTheorems_count_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceTheoremTitles_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceTheoremLabels_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceLabels_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceDocumentKey_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceSupport_length_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceSupport_obligations_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceSupport_documentKeys_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceSupport_labelLists_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceSupport_theoremTitleLists_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionSourceSupportPopulatedBool_eq_true
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_length_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_obligations_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_fields_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_projections_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_documentKeys_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_theoremTitleLists_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_labelLists_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionCertificateFieldSource_suppliedFlags_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslation_length_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslation_fields_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslation_anchorFiles_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslation_labelLists_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationLeanTargets_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationSuppliedFlags_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionHypothesisTranslationAllSuppliedBool_eq_false
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSource_length_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSource_fields_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSource_types_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSource_certificateFields_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSource_anchorFiles_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSource_labelLists_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceLeanTargets_match
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceSuppliedFlags_eq
#print axioms ymAPlusFixedLatticeHamiltonianDefinitionWitnessComponentSourceAllSuppliedBool_eq_false
#print axioms ymAPlusLocalDegreesWitnessInputSource_length_eq
#print axioms ymAPlusLocalDegreesWitnessInputSourceFields_match
#print axioms ymAPlusLocalDegreesWitnessInputSourceRoles_match
#print axioms ymAPlusLocalDegreesWitnessInputSourceTargetShapes_match
#print axioms ymAPlusLocalDegreesWitnessInputSourceAnchorFiles_eq
#print axioms ymAPlusLocalDegreesWitnessInputSourceLabelLists_eq
#print axioms ymAPlusLocalDegreesWitnessInputSourceFinalLabels_match
#print axioms ymAPlusLocalDegreesWitnessInputSourceSupportRoles_eq
#print axioms ymAPlusLocalDegreesWitnessInputSourceSuppliedFlags_eq
#print axioms ymAPlusLocalDegreesWitnessInputSourceAllSuppliedBool_eq_false
#print axioms ymAPlusLocalDegreesWitnessFieldDependencies_length_eq
#print axioms ymAPlusLocalDegreesWitnessFieldDependencyFields_match
#print axioms ymAPlusLocalDegreesWitnessFieldDependencyProjections_match
#print axioms ymAPlusLocalDegreesWitnessFieldDependencyLabelLists_match
#print axioms ymAPlusLocalDegreesWitnessFieldDependencyClasses_eq
#print axioms ymAPlusLocalDegreesWitnessFieldDependencyBlockingFlags_eq
#print axioms ymAPlusLocalDegreesWitnessFieldDependencySuppliedFlags_eq
#print axioms ymAPlusLocalDegreesWitnessFieldDependenciesAllBlockingBool_eq_true
#print axioms ymAPlusLocalDegreesWitnessFieldDependenciesAllSuppliedBool_eq_false
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_target_eq
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_target_matches_constructorName
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_dependencyCount_eq
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_requiredDependencyCount_eq
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_allFieldsMapped_eq_true
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_allDependenciesBlocking_eq_true
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_allDependenciesSupplied_eq_false
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_proofField_eq
#print axioms ymAPlusLocalDegreesWitnessConstructorReadiness_readyForConstructor_eq_false
#print axioms ymAPlusLocalDegreesWitnessConstructorReadinessFlags_eq
#print axioms ymAPlusSourceCrosswalk_length
#print axioms ymAPlusSourceCrosswalk_obligations_match_ledger
#print axioms ymAPlusSourceCrosswalk_titles_match_ledger
#print axioms ymAPlusSourceCrosswalk_currentSockets_match_ledger
#print axioms ymAPlusSourceCrosswalk_requiredClosures_match_ledger
#print axioms ymAPlusSourceCrosswalk_auditFiles_match_focused_obligation_audits
#print axioms ymAPlusSourceCrosswalk_standardImportFiles_match_canonical
#print axioms ymAPlusSourceCrosswalk_subobligationLedgers_match_canonical
#print axioms ymAPlusSourceCrosswalk_certificateTypes_match_canonical
#print axioms ymAPlusSourceCrosswalk_closureGates_match_canonical
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_length_eq
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_titles_match
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_certificateTypes_match
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_certificateProjections_match
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_closureGates_match
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_closureProjections_match
#print axioms ymAPlusAuditedBundleProjectionCrosswalk_populatedBool_eq_true
#print axioms ymAPlusFocusedObligationAuditFiles_count_eq
#print axioms ymAPlusGlobalAuditFiles_count_eq
#print axioms ymAPlusAuditRunnerLeanFiles_count_eq
#print axioms ymAPlusAuditRunnerLeanFiles_decomposes
#print axioms ymAPlusAuditRunnerLeanFiles_match_canonical
#print axioms ymAPlusFocusedObligationAuditFilesDuplicateFreeBool_eq_true
#print axioms ymAPlusGlobalAuditFilesDuplicateFreeBool_eq_true
#print axioms ymAPlusCanonicalAuditRunnerLeanFilesDuplicateFreeBool_eq_true
#print axioms ymAPlusAuditRunnerLeanFilesDuplicateFreeBool_eq_true
#print axioms ymAPlusFocusedGlobalAuditFilesDisjointBool_eq_true
#print axioms ymAPlusAuditRunnerLeanFilesPopulatedBool_eq_true
#print axioms ymAPlusSourceCrosswalk_exactTheoremProjectionCount_eq
#print axioms ymAPlusRequiredVerifiedHypothesisMapNames_count_eq
#print axioms ymAPlusVerifiedHypothesisMapNames_count_eq
#print axioms ymAPlusRequiredVerifiedHypothesisMapNamesPopulatedBool_eq_true
#print axioms ymAPlusRequiredVerifiedHypothesisMapNamesDuplicateFreeBool_eq_true
#print axioms ymAPlusHypothesisMapGapCrosswalk_length_eq
#print axioms ymAPlusHypothesisMapGapCrosswalk_titles_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_currentSockets_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_standardImportFiles_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_firstOpenSubobligations_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_exactTheoremProjections_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_routeHypothesisMaps_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_completionProjections_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_requiredMaps_match
#print axioms ymAPlusHypothesisMapGapCrosswalk_verifiedFlags_eq
#print axioms ymAPlusHypothesisMapGapCrosswalk_allOpenBool_eq_true
#print axioms ymAPlusSourceCrosswalk_payloadProjectionCount_eq
#print axioms ymAPlusSourceCrosswalk_payloadBridgeProjectionCount_eq
#print axioms ymAPlusSourceCrosswalk_standardSocketProjectionCount_eq
#print axioms ymAPlusSourceCrosswalk_finalTargetProjectionCount_eq
#print axioms ymAPlusSourceCrosswalk_globalAuditSurfaceProjectionCount_eq
#print axioms ymAPlusSourceCrosswalk_majorColumnCountsComplete_holds
#print axioms ymAPlusSourceCrosswalk_subobligationCounts_match_ledger
#print axioms ymAPlusSourceCrosswalk_subobligationTotalCount_eq
#print axioms ymAPlusSourceCrosswalk_entries_match_bool_eq_true
#print axioms ymAPlusSourceCrosswalk_entries_have_audit_surface_bool_eq_true
#print axioms ymAPlusSourceCrosswalk_globalAuditSurfacePopulatedBool_eq_true
#print axioms ymAPlusSourceCrosswalk_auditComplete_holds

end YangMills
end Papers
end MaleyLean
