import MaleyLean.Papers.YangMills.APlusStemToSternTarget

namespace MaleyLean
namespace Papers
namespace YangMills

#print axioms APlusStemToSternClayEndpoint.obligationClosed
#print axioms APlusStemToSternClayEndpoint.certificatesAvailable
#print axioms APlusStemToSternClayEndpoint.subobligationsClosed
#print axioms APlusStemToSternClayEndpoint.exactTheoremsAvailable
#print axioms APlusStemToSternClayEndpoint.exactTheoremWitnessCount_eq
#print axioms APlusStemToSternClayEndpoint.nonDependentStandardSocketsAvailable
#print axioms APlusStemToSternClayEndpoint.clayExtensionStandardTransferAvailable
#print axioms APlusStemToSternClayEndpoint.nonDependentPayloadsAvailable
#print axioms APlusStemToSternClayEndpoint.clayExtensionPayloadBridgeAvailable
#print axioms APlusStemToSternClayEndpoint.auditSurfaceComplete_holds
#print axioms APlusStemToSternClayEndpoint.requires_fixed_lattice_gap
#print axioms APlusStemToSternClayEndpoint.requires_sharp_local_construction
#print axioms APlusStemToSternClayEndpoint.requires_continuum_transport
#print axioms APlusStemToSternClayEndpoint.requires_os_wightman_reconstruction
#print axioms APlusStemToSternClayEndpoint.requires_minkowski_hamiltonian_gap
#print axioms APlusStemToSternClayEndpoint.requires_endpoint_exactness_exclusion
#print axioms APlusStemToSternClayEndpoint.requires_clay_extension_admissibility
#print axioms promoteStemToSternToAPlus
#print axioms ymAPlusObligationsClosed_of_auditedBundle
#print axioms promoteStemToSternToAPlus_of_auditedBundle
#print axioms promoteStemToSternToAPlus_of_auditTargets
#print axioms promoteStemToSternToAPlus_nonempty_of_auditTargets

end YangMills
end Papers
end MaleyLean
