import MaleyLean.Papers.YangMills.Kernel.APlusClosureProtocol

namespace MaleyLean
namespace Papers
namespace YangMills

#check YMAuditedAPlusCertificateBundle
#eval ymAPlusAuditedBundleCertificateProjectionNames
#eval ymAPlusAuditedBundleSubobligationProjectionNames
#eval ymAPlusAuditedBundleProjectionNames
#eval ymAPlusAuditedBundleProjectionNamesDuplicateFreeBool
#eval ymAPlusAuditedBundleProjectionNamesPopulatedBool
#print axioms YMAuditedAPlusCertificateBundle.ofAuditTargets
#print axioms ymAPlusAuditedBundle_nonempty_of_auditTargets
#print axioms YMAuditedAPlusCertificateBundle.certificatesAvailable
#print axioms YMAuditedAPlusCertificateBundle.subobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.auditTargets
#print axioms ymAPlusAuditedBundleCertificateProjectionNames_count_eq
#print axioms ymAPlusAuditedBundleSubobligationProjectionNames_count_eq
#print axioms ymAPlusAuditedBundleProjectionNames_count_eq
#print axioms ymAPlusAuditedBundleProjectionNamesDuplicateFreeBool_eq_true
#print axioms ymAPlusAuditedBundleProjectionNamesPopulatedBool_eq_true
#print axioms YMAuditedAPlusCertificateBundle.fixedLatticeGapCertificate
#print axioms YMAuditedAPlusCertificateBundle.sharpLocalCertificate
#print axioms YMAuditedAPlusCertificateBundle.continuumTransportCertificate
#print axioms YMAuditedAPlusCertificateBundle.osWightmanCertificate
#print axioms YMAuditedAPlusCertificateBundle.minkowskiHamiltonianGapCertificate
#print axioms YMAuditedAPlusCertificateBundle.endpointExactnessCertificate
#print axioms YMAuditedAPlusCertificateBundle.clayExtensionCertificate
#print axioms YMAuditedAPlusCertificateBundle.fixedLatticeGapSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.sharpLocalSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.continuumTransportSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.osWightmanSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.minkowskiHamiltonianGapSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.endpointExactnessSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.clayExtensionSubobligationsClosed
#print axioms YMAuditedAPlusCertificateBundle.exactTheoremsAvailable
#print axioms YMAuditedAPlusCertificateBundle.exactTheoremWitnessCount_eq
#print axioms YMAuditedAPlusCertificateBundle.nonDependentStandardSocketsAvailable
#print axioms YMAuditedAPlusCertificateBundle.clayExtensionStandardTransferAvailable
#print axioms YMAuditedAPlusCertificateBundle.nonDependentPayloadsAvailable
#print axioms YMAuditedAPlusCertificateBundle.clayExtensionPayloadBridgeAvailable
#print axioms YMAuditedAPlusCertificateBundle.nonDependentAuditSurfaceComplete_holds
#print axioms ymAuditedClayExtensionSubobligationsClosed_of_standard_import
#print axioms YMAuditedAPlusCertificateBundle.clayExtensionSubobligationsClosed_of_standard_import
#print axioms YMAuditedAPlusCertificateBundle.clayExtensionCertificateAvailable_of_standard_import

end YangMills
end Papers
end MaleyLean
