import MaleyLean.Papers.BivalenceNonDegenerateReasoning
import MaleyLean.Papers.ClaimStandingAndLegitimacy
import MaleyLean.Papers.FormalizationSmokeTest
import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction
